# SPDX-FileCopyrightText: 2026 Bruno Venceslau
# SPDX-License-Identifier: GPL-3.0-only

# The license of each file that carries no SPDX header of its own
# (REUSE 3.3). The product is GPL-3.0-only; examples/ and schemas/
# are CC0-1.0, because users copy them into their own config repos.

version = 1

[[annotations]]
path = [
    "README.md",
    "docs/**",
    ".adr-dir",
    ".githooks/pre-push",
    "go.mod",
    "go.sum",
    "mise.lock",
]
SPDX-FileCopyrightText = "2026 Bruno Venceslau"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = ["examples/**", "schemas/**"]
SPDX-FileCopyrightText = "2026 Bruno Venceslau"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "COPYING"
SPDX-FileCopyrightText = "2007 Free Software Foundation, Inc. <https://fsf.org/>"
SPDX-License-Identifier = "GPL-3.0-only"
