// SPDX-FileCopyrightText: 2026 Bruno Venceslau
// SPDX-License-Identifier: GPL-3.0-only

package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const goodADR = "# 7. Adopt a thing\n\nDate: 2026-10-08\n\n## Status\n\nAccepted\n\n## Context\n\nx\n"

// TestParseADR covers the title line, the number agreement and each way
// the status is written.
func TestParseADR(t *testing.T) {
	tests := []struct {
		name    string
		file    string
		content string
		want    adr
		err     string
	}{
		{"accepted", "0007-adopt-a-thing.md", goodADR, adr{"0007-adopt-a-thing.md", 7, "Adopt a thing", "Accepted"}, ""},
		{"proposed with CR LF", "0007-x.md", "# 7. T\r\n\r\n## Status\r\n\r\nProposed\r\n", adr{"0007-x.md", 7, "T", "Proposed"}, ""},
		{"a rejection with its reason", "0007-x.md", "# 7. T\n\n## Status\n\nRejected\n\nThe maintainer declined it.\n", adr{"0007-x.md", 7, "T", "Rejected"}, ""},
		{"superseded by a later record", "0007-x.md", "# 7. T\n\n## Status\n\nAccepted\n\nSuperseded by [9. U](0009-u.md)\n\n## Context\n", adr{"0007-x.md", 7, "T", "Superseded"}, ""},
		{"a Superseded by line after the section is not the status", "0007-x.md", "# 7. T\n\n## Status\n\nAccepted\n\n## Context\n\nSuperseded by nobody\n", adr{"0007-x.md", 7, "T", "Accepted"}, ""},
		{"the status after another section", "0007-x.md", "# 7. T\n\n## Context\n\nAccepted\n\n## Status\n\nDeprecated\n", adr{"0007-x.md", 7, "T", "Deprecated"}, ""},
		{"a filename that is no record", "x.md", goodADR, adr{}, "not NNNN-slug.md"},
		{"no title line", "0007-x.md", "Date: x\n", adr{}, "not \"# N. Title\""},
		{"the number differs from the filename", "0008-x.md", goodADR, adr{}, "numbers the record 7, and the filename 8"},
		{"no status section", "0007-x.md", "# 7. T\n\n## Context\n", adr{}, "no \"## Status\" section"},
		{"an empty status section", "0007-x.md", "# 7. T\n\n## Status\n\n## Context\n", adr{}, "no status under"},
		{"a status outside the set", "0007-x.md", "# 7. T\n\n## Status\n\nDraft\n", adr{}, `the status "Draft" is not one of`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseADR(tt.file, []byte(tt.content))
			if tt.err != "" {
				require.ErrorContains(t, err, tt.err)
				return
			}
			require.NoError(t, err)
			assert.Equal(t, tt.want, got)
		})
	}
}

// TestADRIndex checks the rows, the escapes in a title, and the header.
func TestADRIndex(t *testing.T) {
	got := string(adrIndex([]adr{
		{"0001-a.md", 1, "First", "Accepted"},
		{"0002-b.md", 2, "Use [x] | y", "Proposed"},
	}))
	assert.Contains(t, got, "<!-- Generated by \"go generate ./...\" from the titles and statuses of the records in this directory. Do not edit by hand. -->\n")
	assert.Contains(t, got, "| 1 | [First](0001-a.md) | Accepted |\n")
	assert.Contains(t, got, "| 2 | [Use \\[x\\] \\| y](0002-b.md) | Proposed |\n")
}
