// SPDX-FileCopyrightText: 2026 Bruno Venceslau
// SPDX-License-Identifier: GPL-3.0-only

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// validAskFirst is the smallest list that passes: one surface, which is
// the list itself.
const validAskFirst = `version: 1
owner: "@someone"
surfaces:
  - id: ask-first
    globs: [.github/ask-first.yaml]
    reason: this list
`

// TestParseAskFirst checks each rule of the file with one source that
// breaks it: the keys, the version, the owner, the ids, the globs, the
// reason, and the line that makes the file list itself.
func TestParseAskFirst(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want string // a part of the error; empty means it parses
	}{
		{"valid", validAskFirst, ""},
		{"two surfaces and a team owner", strings.Replace(validAskFirst, "@someone", "@org/team", 1) + "  - id: gates\n    globs: [internal/gate/**, go.mod, a/*/b.go]\n    reason: the gates\n", ""},
		{"not YAML", "version: [", "ask-first.yaml"},
		{"an unknown key", validAskFirst + "extra: 1\n", "field extra not found"},
		{"a second document", validAskFirst + "---\nversion: 1\n", "more than one YAML document"},
		{"version 2", strings.Replace(validAskFirst, "version: 1", "version: 2", 1), "version is 2"},
		{"no version", strings.Replace(validAskFirst, "version: 1\n", "", 1), "version is 0"},
		{"owner without @", strings.Replace(validAskFirst, "@someone", "someone", 1), "not a GitHub handle"},
		{"owner with a space", strings.Replace(validAskFirst, "@someone", "@some one", 1), "not a GitHub handle"},
		{"no surface", "version: 1\nowner: \"@o\"\nsurfaces: []\n", "no surface is listed"},
		{"a bad id", strings.Replace(validAskFirst, "id: ask-first", "id: Ask_First", 1), "not lowercase words"},
		{"a duplicate id", validAskFirst + "  - id: ask-first\n    globs: [a]\n    reason: again\n", "listed twice"},
		{"no glob", validAskFirst + "  - id: other\n    globs: []\n    reason: x\n", `surface "other" has no glob`},
		{"no reason", validAskFirst + "  - id: other\n    globs: [a]\n    reason: \" \"\n", "needs a reason"},
		{"a reason on two lines", validAskFirst + "  - id: other\n    globs: [a]\n    reason: |\n      a\n      b\n", "needs a reason written on one line"},
		{"a leading slash", validAskFirst + "  - id: other\n    globs: [/a]\n    reason: x\n", "starts or ends with"},
		{"a character class", validAskFirst + "  - id: other\n    globs: [\"a/[bc]\"]\n    reason: x\n", "holds a character other than"},
		{"a negation", validAskFirst + "  - id: other\n    globs: [\"!a\"]\n    reason: x\n", "holds a character other than"},
		{"a partial double star", validAskFirst + "  - id: other\n    globs: [a**/b]\n    reason: x\n", `"**" must be a whole segment`},
		{"a dot dot", validAskFirst + "  - id: other\n    globs: [a/../b]\n    reason: x\n", "empty, \".\" or \"..\""},
		{"an empty glob", validAskFirst + "  - id: other\n    globs: [\"\"]\n    reason: x\n", "a glob is empty"},
		{"the file does not list itself", strings.Replace(validAskFirst, ".github/ask-first.yaml", "elsewhere", 1), "the file lists itself"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			list, err := parseAskFirst([]byte(tt.src))
			if tt.want == "" {
				require.NoError(t, err)
				assert.NotNil(t, list)
				return
			}
			require.ErrorContains(t, err, tt.want)
		})
	}
}

// TestCodeowners checks the lines of CODEOWNERS: the notice, every glob
// anchored at the root and given to the owner, in the order of the file.
func TestCodeowners(t *testing.T) {
	list, err := parseAskFirst([]byte(validAskFirst + "  - id: mods\n    globs: [go.mod, internal/x/**]\n    reason: x\n"))
	require.NoError(t, err)
	want := `# Generated by "go generate ./..." from .github/ask-first.yaml. Do not edit by hand.
# A change to a path below needs the maintainer's review before it merges
# (docs/reference/ask-first.md lists the surfaces and their reasons).

# ask-first
/.github/ask-first.yaml @someone

# mods
/go.mod @someone
/internal/x/** @someone
`
	assert.Equal(t, want, string(list.codeowners()))
}

// TestReferencePage checks the generated page: the front matter of rule
// 1 of ADR 0001 comes first, the header follows, and a "|" in a reason
// does not split a table cell.
func TestReferencePage(t *testing.T) {
	list, err := parseAskFirst([]byte(validAskFirst + "  - id: mods\n    globs: [go.mod, internal/x/**]\n    reason: a | b\n"))
	require.NoError(t, err)
	page := string(list.referencePage())
	assert.True(t, strings.HasPrefix(page, "---\ntype: reference\nreader: "), "front matter first")
	assert.Contains(t, page, "\n---\n\n<!-- Generated by \"go generate ./...\" from .github/ask-first.yaml. Do not edit by hand. -->\n")
	assert.Contains(t, page, "| `ask-first` | `.github/ask-first.yaml` | this list |\n")
	assert.Contains(t, page, "| `mods` | `go.mod`, `internal/x/**` | a \\| b |\n")
	assert.Contains(t, page, "`@someone`")
}

// TestAskFirstOfThisRepository parses the committed list and checks that
// the committed consumers are what it produces, so a hand edit of either
// fails here before it fails "generated".
func TestAskFirstOfThisRepository(t *testing.T) {
	root := moduleRoot(t)
	outputs, err := generateOutputs(root)
	require.NoError(t, err)
	require.Len(t, outputs, 3)
	for _, out := range outputs {
		got, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(out.path)))
		require.NoError(t, err, out.path)
		assert.Equal(t, string(out.content), string(got), "%s is current", out.path)
	}
}

// TestPullRequestTemplate checks the five sections of 12 12.7, in order.
func TestPullRequestTemplate(t *testing.T) {
	b, err := os.ReadFile(filepath.Join(moduleRoot(t), ".github", "pull_request_template.md"))
	require.NoError(t, err)
	var got []string
	for _, line := range strings.Split(string(b), "\n") {
		if h, ok := strings.CutPrefix(line, "## "); ok {
			got = append(got, h)
		}
	}
	assert.Equal(t, []string{"Why", "What changed", "Evidence", "Middleware", "Lessons"}, got)
}
