// SPDX-FileCopyrightText: 2026 Bruno Venceslau
// SPDX-License-Identifier: GPL-3.0-only

package main

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// validAskFirst is the smallest list that passes: one surface, which is
// the list itself.
const validAskFirst = `version: 1
owner: "@someone"
surfaces:
  - id: ask-first
    globs: [.github/ask-first.yaml]
    reason: this list
`

// TestParseAskFirst checks each rule of the file with one source that
// breaks it: the keys, the version, the owner, the ids, the globs, the
// reason, and the line that makes the file list itself.
func TestParseAskFirst(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want string // a part of the error; empty means it parses
	}{
		{"valid", validAskFirst, ""},
		{"two surfaces and a team owner", strings.Replace(validAskFirst, "@someone", "@org/team", 1) + "  - id: gates\n    globs: [internal/gate/**, go.mod, a/*/b.go]\n    reason: the gates\n", ""},
		{"not YAML", "version: [", "ask-first.yaml"},
		{"an unknown key", validAskFirst + "extra: 1\n", "field extra not found"},
		{"a second document", validAskFirst + "---\nversion: 1\n", "more than one YAML document"},
		{"version 2", strings.Replace(validAskFirst, "version: 1", "version: 2", 1), "version is 2"},
		{"no version", strings.Replace(validAskFirst, "version: 1\n", "", 1), "version is 0"},
		{"owner without @", strings.Replace(validAskFirst, "@someone", "someone", 1), "not a GitHub handle"},
		{"owner with a space", strings.Replace(validAskFirst, "@someone", "@some one", 1), "not a GitHub handle"},
		{"no surface", "version: 1\nowner: \"@o\"\nsurfaces: []\n", "no surface is listed"},
		{"a bad id", strings.Replace(validAskFirst, "id: ask-first", "id: Ask_First", 1), "not lowercase words"},
		{"a duplicate id", validAskFirst + "  - id: ask-first\n    globs: [a]\n    reason: again\n", "listed twice"},
		{"no glob", validAskFirst + "  - id: other\n    globs: []\n    reason: x\n", `surface "other" has no glob`},
		{"no reason", validAskFirst + "  - id: other\n    globs: [a]\n    reason: \" \"\n", "needs a reason"},
		{"a reason on two lines", validAskFirst + "  - id: other\n    globs: [a]\n    reason: |\n      a\n      b\n", "needs a reason written on one line"},
		{"a leading slash", validAskFirst + "  - id: other\n    globs: [/a]\n    reason: x\n", "starts or ends with"},
		{"a character class", validAskFirst + "  - id: other\n    globs: [\"a/[bc]\"]\n    reason: x\n", "holds a character other than"},
		{"a negation", validAskFirst + "  - id: other\n    globs: [\"!a\"]\n    reason: x\n", "holds a character other than"},
		{"a partial double star", validAskFirst + "  - id: other\n    globs: [a**/b]\n    reason: x\n", `"**" must be a whole segment`},
		{"a dot dot", validAskFirst + "  - id: other\n    globs: [a/../b]\n    reason: x\n", "empty, \".\" or \"..\""},
		{"an empty glob", validAskFirst + "  - id: other\n    globs: [\"\"]\n    reason: x\n", "a glob is empty"},
		{"the file does not list itself", strings.Replace(validAskFirst, ".github/ask-first.yaml", "elsewhere", 1), "the file lists itself"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			list, err := parseAskFirst([]byte(tt.src))
			if tt.want == "" {
				require.NoError(t, err)
				assert.NotNil(t, list)
				return
			}
			require.ErrorContains(t, err, tt.want)
		})
	}
}

// TestCodeowners checks the lines of CODEOWNERS: the notice, every glob
// anchored at the root and given to the owner, in the order of the file.
func TestCodeowners(t *testing.T) {
	list, err := parseAskFirst([]byte(validAskFirst + "  - id: mods\n    globs: [go.mod, internal/x/**]\n    reason: x\n"))
	require.NoError(t, err)
	want := `# Generated by "go generate ./..." from .github/ask-first.yaml. Do not edit by hand.
# A change to a path below needs the maintainer's review before it merges
# (docs/reference/ask-first.md lists the surfaces and their reasons).

# ask-first
/.github/ask-first.yaml @someone

# mods
/go.mod @someone
/internal/x/** @someone
`
	assert.Equal(t, want, string(list.codeowners()))
}

// TestReferencePage checks the generated page: the front matter of rule
// 1 of ADR 0001 comes first, the header follows, and a "|" in a reason
// does not split a table cell.
func TestReferencePage(t *testing.T) {
	list, err := parseAskFirst([]byte(validAskFirst + "  - id: mods\n    globs: [go.mod, internal/x/**]\n    reason: a | b\n"))
	require.NoError(t, err)
	page := string(list.referencePage())
	assert.True(t, strings.HasPrefix(page, "---\ntype: reference\nreader: "), "front matter first")
	assert.Contains(t, page, "\n---\n\n<!-- Generated by \"go generate ./...\" from .github/ask-first.yaml. Do not edit by hand. -->\n")
	assert.Contains(t, page, "| `ask-first` | `.github/ask-first.yaml` | this list |\n")
	assert.Contains(t, page, "| `mods` | `go.mod`, `internal/x/**` | a \\| b |\n")
	assert.Contains(t, page, "`@someone`")
	assert.Contains(t, page, "```text\n"+approvalForm+"\n```\n", "the form of 12 12.4")
}

// TestAskFirstOfThisRepository parses the committed list and checks that
// the committed consumers are what it produces, so a hand edit of either
// fails here before it fails "generated".
func TestAskFirstOfThisRepository(t *testing.T) {
	dir := moduleRoot(t)
	root, err := os.OpenRoot(dir)
	require.NoError(t, err)
	t.Cleanup(func() { _ = root.Close() })
	outputs, err := generateOutputs(root)
	require.NoError(t, err)
	require.Len(t, outputs, 3)
	for _, out := range outputs {
		got, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(out.path)))
		require.NoError(t, err, out.path)
		assert.Equal(t, string(out.content), string(got), "%s is current", out.path)
	}
}

// TestPullRequestTemplate checks the five sections of 12 12.7, in order,
// and the approval hint: the template shows the form of 12 12.4 inside a
// sentence, so a body that keeps the hint has no line that starts with
// "Approval: ", which pr would read as a malformed approval line.
func TestPullRequestTemplate(t *testing.T) {
	b, err := os.ReadFile(filepath.Join(moduleRoot(t), ".github", "pull_request_template.md"))
	require.NoError(t, err)
	var got []string
	for _, line := range strings.Split(string(b), "\n") {
		if h, ok := strings.CutPrefix(line, "## "); ok {
			got = append(got, h)
		}
		assert.False(t, strings.HasPrefix(line, "Approval: "), "a line that starts with the prefix: %q", line)
	}
	assert.Equal(t, []string{"Why", "What changed", "Evidence", "Middleware", "Lessons"}, got)
	assert.Contains(t, string(b), approvalForm)
}

// TestApprovalLineOfTheSpec checks that 12 12.4 shows the form and the
// regular expression that approvalLine holds, and that the form itself
// is not an approval line.
func TestApprovalLineOfTheSpec(t *testing.T) {
	b, err := os.ReadFile(filepath.Join(moduleRoot(t), "docs", "spec", "12-engineering.md"))
	require.NoError(t, err)
	spec := strings.ReplaceAll(string(b), "\r\n", "\n")
	assert.Contains(t, spec, "```text\n"+approvalForm+"\n```\n")
	assert.Contains(t, spec, "```text\n"+approvalLine.String()+"\n```\n")
	assert.False(t, approvalLine.MatchString(approvalForm))
}

// TestApprovalLine checks approvalLine on one line at a time; how pr
// reads the lines of a whole body is T005's.
func TestApprovalLine(t *testing.T) {
	cases := []struct {
		name, line string
		match      bool
	}{
		{"a valid line", "Approval: decisions - amend rule 8", true},
		{"an apostrophe", "Approval: decisions - the record\u2019s rule 8", true},
		{"a single straight quote", "Approval: decisions - the 'rule 8' text", true},
		{"a lowercase prefix", "approval: decisions - amend rule 8", false},
		{"an uppercase id", "Approval: Decisions - amend rule 8", false},
		{"an en dash separator", "Approval: decisions \u2013 amend rule 8", false},
		{"an empty phrase", "Approval: decisions - ", false},
		{"a straight quote around the phrase", "Approval: decisions - \"amend rule 8\"", false},
		{"a straight quote inside the phrase", "Approval: decisions - amend \"rule 8", false},
		{"a left curly quote alone", "Approval: decisions - \u201camend rule 8", false},
		{"a right curly quote alone", "Approval: decisions - amend rule 8\u201d", false},
		{"a low double quote", "Approval: decisions - \u201eamend rule 8", false},
		{"guillemets", "Approval: decisions - \u00abamend rule 8\u00bb", false},
		{"a double prime", "Approval: decisions - amend rule 8\u2033", false},
		{"a fullwidth quote", "Approval: decisions - \uff02amend rule 8", false},
		{"a CJK double prime quote", "Approval: decisions - \u301damend rule 8\u301e", false},
		{"a leading no-break space", "Approval: decisions - \u00a0amend rule 8", false},
		{"a leading tab", "Approval: decisions - \tamend rule 8", false},
		{"a trailing CR", "Approval: decisions - amend rule 8\r", false},
		{"an embedded LF", "Approval: decisions - amend\nrule 8", false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			assert.Equal(t, c.match, approvalLine.MatchString(c.line))
		})
	}
}

// specAskFirstList returns the YAML fence under "5.3 Ask-first surfaces"
// in the security chapter of the specification: the first fence after
// that heading and before the next one.
func specAskFirstList(t *testing.T) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(moduleRoot(t), "docs", "spec", "05-security.md"))
	require.NoError(t, err)
	_, section, found := strings.Cut(string(b), "\n## 5.3 Ask-first surfaces\n")
	require.True(t, found, "the heading of 5.3")
	if end := strings.Index(section, "\n## "); end >= 0 {
		section = section[:end]
	}
	_, fence, found := strings.Cut(section, "\n```yaml\n")
	require.True(t, found, "a yaml fence under 5.3")
	list, _, found := strings.Cut(fence, "\n```\n")
	require.True(t, found, "the fence ends")
	return list + "\n"
}

// TestSpecListIsTheCommittedList checks that the list that 05 5.3 shows
// and .github/ask-first.yaml say the same: the same surfaces, in the
// same order, with the same globs and reasons. The spec writes the owner
// as the placeholder "@<owner>" (the module path's owner, 02 2.1), so
// the committed owner stands in for it. Two copies of a list drift
// unless a test holds them together.
func TestSpecListIsTheCommittedList(t *testing.T) {
	committed, err := os.ReadFile(filepath.Join(moduleRoot(t), filepath.FromSlash(askFirstPath)))
	require.NoError(t, err)
	want, err := parseAskFirst(committed)
	require.NoError(t, err)
	fence := specAskFirstList(t)
	require.Contains(t, fence, `owner: "@<owner>"`, "the spec names the owner by its placeholder")
	got, err := parseAskFirst([]byte(strings.Replace(fence, "@<owner>", want.Owner, 1)))
	require.NoError(t, err)
	assert.Equal(t, want, got)
}

// TestGlobMatch pins the matcher of the ask-first dialect: "**" is zero
// or more whole segments, "*" a run inside one segment.
func TestGlobMatch(t *testing.T) {
	tests := []struct {
		glob, name string
		want       bool
	}{
		{"go.mod", "go.mod", true},
		{"go.mod", "x/go.mod", false},
		{"mise.*.toml", "mise.local.toml", true},
		{"mise.*.toml", "mise.toml", false},
		{"mise.*.toml", "mise.a/b.toml", false},
		{".mise.*.toml", ".mise.ci.local.toml", true},
		{"mise/**", "mise/config.toml", true},
		{"mise/**", "mise/conf.d/x.toml", true},
		{"mise/**", "mise", true},
		{"mise/**", "x/mise/config.toml", false},
		{"a/**/b", "a/b", true},
		{"a/**/b", "a/x/y/b", true},
		{"a/**/b", "a/x/y/c", false},
		{"*", ".hidden", true},
	}
	for _, tt := range tests {
		assert.Equal(t, tt.want, globMatch(tt.glob, tt.name), "%s ~ %s", tt.glob, tt.name)
	}
}

// TestCodeownersAsksFirst holds the ask-first surface of the committed
// list to the list itself and the CODEOWNERS file generated from it: a
// change to CODEOWNERS asks for the review even where generated does
// not judge the commit, as when a step that runs before it rewrote the
// index (05 5.3).
func TestCodeownersAsksFirst(t *testing.T) {
	src, err := os.ReadFile(filepath.Join(moduleRoot(t), askFirstPath))
	require.NoError(t, err)
	list, err := parseAskFirst(src)
	require.NoError(t, err)
	i := slices.IndexFunc(list.Surfaces, func(s surface) bool { return s.ID == "ask-first" })
	require.GreaterOrEqual(t, i, 0, "the ask-first surface")
	assert.Equal(t, []string{askFirstPath, codeownersPath}, list.Surfaces[i].Globs)
}
